# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start Postgres service
      run: |
        docker run --name postgres -e POSTGRES_DB=assistant_db -e POSTGRES_USER=assistant_user -e POSTGRES_PASSWORD=abc123 -d -p 5432:5432 postgres:latest
        sleep 10 # wait for Postgres to start

    - name: Test with pytest
      env:
        DATABASE_URL: postgresql://assistant_user:abc123@postgres:5432/assistant_db
      run: |
        pytest

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics